($sec, $min, $hour, $mday, $mon, $year, $nedela, )=localtime;
if ($mday < 10 ) { $mdays="0"; $mday="$mdays$mday";}
if ($min < 10 ) { $mins="0"; $min="$mins$min";}
$mon++; if ($mon < "10") {$mon="0$mon";}
$year=1900+$year;

$today="$mday-$mon-$year";
$time="$hour:$min";
$today_time="$mday-$mon-$year\_$hour-$min-$sec";
$today_sql="$year-$mon-$mday $hour:$min:$sec";
$ip=$ENV{'REMOTE_ADDR'};
$host=$ENV{'HTTP_HOST'};  
$admin_host="http://uplecms.ru";
$dirs="layouts";
$hide_valuta="1";
$hide_pogoda="1";
$hide_metal="1";
$hide_callback="0";
$hide_phone1_set="0";
$hide_phone2_set="1";
$hide_address_set="1";
$hide_timemode_set="1";
$hide_copyright_set="0";
$hide_makets="0";
$hide_templates="0";
$hide_templates_opt="1";
$hide_category_photo="0";
$hide_news_photo="1";
$hide_articles="0";
$hide_articles_parent="1";
$hide_banners="1";	
$hide_banners_designer="1";
$banners_gor_width="751";
$banners_gor_height="164";
$banners_ver_width="184";
$banners_ver_height="364";
$hide_gallery_ext="1";
$hide_gallery_lite="1";
$hide_gallery_watermark="1";
$hide_slideshow_edit="1";
$hide_products_price="0";
$hide_products_old_price="1";
$hide_products_sort="1";
$hide_products_f_price="1";
$hide_products_view="1";
$hide_products_raiting="1";
$hide_products_reviews="1";
$hide_products_search="1";
$hide_products_search_help="1";
$hide_products_hit="0";
$hide_products_spec="0";
$hide_products_new="0";
$hide_products_art="0";
$hide_products_avail="0";
$hide_products_social="1";
$hide_products_watermark="0";
$hide_products_multi_add="0";
$hide_products_yaimages="1";
$hide_products_yamarket="0";
$hide_products_compare="1";
$hide_products_navigation="1";
$hide_products_recomend="0";
$hide_products_related="0";
$hide_products_viewed="0";
$hide_products_random="1";
$hide_more_photo="0";
$resize_photo_single="1";
$resize_more_photo_smart="0";
$hide_products_zoom="1";
$pr_zoom_color="white";
$hide_products_type="1";
$pr_type_name="Απενδϋ";
$pr_type_name_sm="Απενδ";
$hide_products_param="0";
$hide_products_filter="0";
$hide_payment_set="1";
$hide_private="0";
$surely_register="0";
$hide_fadepage="1";

require "set_parametrs";
require "versions";

-1;
